//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuMuon
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaPhieuMuon { get; set; }
        public Nullable<int> MaSach { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string TinhTrangMuon { get; set; }
        public string TinhTrangTra { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
