//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
        }
    
        public int MaDocGia { get; set; }
        public string HoTen { get; set; }
        public string MaSinhVien { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> SoSachDangMuon { get; set; }
        public Nullable<int> TongSachDaMuon { get; set; }
    
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
    }
}
