//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeSach
    {
        public KeSach()
        {
            this.Saches = new HashSet<Sach>();
        }
    
        public int MaKe { get; set; }
        public string TenKe { get; set; }
        public Nullable<int> MaKho { get; set; }
        public string ViTri { get; set; }
        public Nullable<int> SucChua { get; set; }
        public Nullable<int> SoLuongHienTai { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
