//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public Kho()
        {
            this.KeSaches = new HashSet<KeSach>();
        }
    
        public int MaKho { get; set; }
        public string TenKho { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SucChua { get; set; }
        public Nullable<int> SoLuongHienTai { get; set; }
        public string MoTa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<KeSach> KeSaches { get; set; }
    }
}
