//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
            this.PhieuNhapKhoes = new HashSet<PhieuNhapKho>();
        }
    
        public int MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string ChucVu { get; set; }
        public string PhongBan { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        public virtual ICollection<PhieuNhapKho> PhieuNhapKhoes { get; set; }
    }
}
