//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        public int MaPhieuTra { get; set; }
        public Nullable<int> MaPhieuMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoNgayTre { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public string LyDoPhiPhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
