//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapKho
    {
        public PhieuNhapKho()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public int MaPhieu { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string NhaCungCap { get; set; }
        public string NguoiNhap { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> SoLuongSach { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
