//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public PhieuMuon()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
            this.PhieuTras = new HashSet<PhieuTra>();
        }
    
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaDocGia { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayHenTra { get; set; }
        public Nullable<System.DateTime> NgayTraThucTe { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> SoLuongSach { get; set; }
        public Nullable<decimal> PhiPhat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual DocGia DocGia { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<PhieuTra> PhieuTras { get; set; }
    }
}
