//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVienNhom12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public Sach()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<decimal> GiaBia { get; set; }
        public string MoTa { get; set; }
        public string TuKhoa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> MaKe { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongCoSan { get; set; }
        public Nullable<int> LuotMuon { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual KeSach KeSach { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
